language: java
jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "LUWmxKbyyjFzQOOKf2RUP90LzKQcCZWFZSyH4n7Fi+AJWIAqR/a6eAqJrOMV7BavAPjlxkH9WGG74fiRGBkWM++5832KYN6hLz5ulGrUXkY/yqlynr13mJmsslvnSUyy9qPPbWOcMqsXN/uyPWrdYGIafr2HnPYDWX+2Z5YhP2c="

addons:
  coverity_scan:
    project:
      name: "kshchepanovskyi/proto-compiler"
      description: "Build submitted via Travis CI"
    notification_email: schepanovsky@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
